//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilaCRMdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vizit
    {
        public int Id { get; set; }
    
        public virtual FIO FIO { get; set; }
        public virtual Anamnez Anamnez { get; set; }
        public virtual Diagnoz Diagnoz { get; set; }
    }
}
